version: '2'

services:
  elasticsearch:
    image: elastic/elasticsearch:7.0.0
    environment:
      discovery.type: single-node

  kibana:
    image: elastic/kibana:7.0.0

  filebeat:
    image: docker.elastic.co/beats/filebeat-oss:7.0.0
    user: root
    volumes:
      - ./filebeat.yml:/usr/share/filebeat/filebeat.yml
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/containers:/var/lib/docker/containers
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
