filebeat.inputs:
  - type: docker
    containers.ids: '*'
    tail_files: ${TAIL_FILES:false}

processors:
  - add_docker_metadata: ~
  - drop_event:
      when:
        or:
          - equals:
              container.labels.io_rancher_stack_service_name: ipsec/ipsec/router
          - equals:
              container.labels.io_rancher_stack_service_name: logging/filebeat
  - include_fields:
      fields:
        - message
        - container.name
        - container.image.name
        - container.labels.com_docker_compose_project
        - container.labels.com_docker_compose_service
        - container.labels.io_rancher_stack_service_name
        - container.labels.io_rancher_stack_name

output.elasticsearch:
  hosts: ${ELASTICSEARCH_URL}

setup.template.settings:
  index:
    number_of_shards: 1
    number_of_replicas: 0

logging.metrics.enabled: false
