filebeat.inputs:
- type: docker
  containers.ids: '*'
  tail_files: ${TAIL_FILES:false}

processors:
- add_docker_metadata: ~
- drop_event:
    when:
      equals:
        container.labels.io_rancher_stack_service_name: ipsec/ipsec/router

output.elasticsearch:
  hosts: ${ELASTICSEARCH_URL}

setup.template.settings:
  index:
    number_of_shards: 1
    number_of_replicas: 0

logging.metrics.enabled: false
